### ISSUE TITLE
Zoznam prihlásených tímov

### ISSUE THREAD

**Issue by cevro** [fykosak/web-fol#1]
Výsledkom by mal byť component, ktorý dostane `eventId` a kategoriu. Stiahne a vypíše všetky tímy v danej kategórii.

Myslieť na rôzne statusy tímov.

Z časti nastrelené.

**Comment by katerinacharvatova** [comment]
Ahoj @vercah , koukala jsem na stránku se seznamem týmů v archivu a je to nějak rozbité a je tam kategorie F a tak. Mohla by ses na to prosím podívat a případně to opravit? :) 
https://beta.online.fyziklani.cz/2017/tymy/

Také mi přijde celkem neintuitivní, že když kliknu na archiv a na příslušný ročník, tak se změní horní lišta. Přišlo by mi pěkné, kdyby se místo změny v horním menu zobrazila nějaká stránka, kde by byla třeba fotka, nebo tak a seznam věcí, ze kterých si můžu vybrat. Takto je to v horním menu a stránka samotná je prázdná, jen je tam divně posunutá dolní lišta asi, která pak bude stejně jiná. Chápu, že je to asi zkopírované z Fyziklání nebo tak, ale asi by to bylo třeba opravit. Nevím, jestli to s tím přímo souvisí, pokud ne, klidně to můžu napsat zvlášť jako jiný úkol. Jen jsem chtěla říct, že to tam chybí :)
