### ISSUE TITLE
Změna ,,archive year homepage''

### ISSUE THREAD

**Issue by katerinacharvatova** [fykosak/web-fol#12]
Když kliknete na archiv a na příslušný ročník, tak se změní horní lišta, což je celkem neintuitivní. Přišlo by mi pěkné, kdyby se místo změny v horním menu zobrazila nějaká stránka, kde by byla třeba fotka, nebo tak a seznam věcí, ze kterých si můžu vybrat. Takto je to v horním menu a stránka samotná je prázdná, jen je tam divně posunutá dolní lišta asi, která pak bude stejně jiná. Chápu, že je to asi zkopírované z Fyziklání nebo tak, ale asi by to bylo třeba opravit. :)

**Comment by vanekm** [comment]
@sstenchlak @katerinacharvatova  Tak co to prostě vzít po vzoru té hlavní stránky od Tomáše, přičemž mapka by samozřejmě zobrazovala přihlášení z toho archivního roku, ale nahradit ten text vlevo "Mezinárodní..." nějakými tlačítky "týmy", "výsledkovky" apod.?

S neměněním menu mi zase přijde, že může být problém, protože když si budeš chtít prohlédnout ročník, asi chceš mít možnost se minimálně vrátit na hlavní stránku toho ročníku (a nemuset se překlikávat přes archiv zpátky na ten ročník, i když to je jen jedno kliknutí navíc). Ale jinak se mi líbí myšlenka ho zachovávat.

**Comment by cevro** [comment]
Tá stránka nemusí byť generická, pre tieto účely je hacknuté načítavanie latte šablon, kde sa dá povedať, že pre daný ročník sa má použť šablona `<action>.<yearKey>.<lang>.latte` alebo `<action>.<yearKey>.latte` pravdaže sa do toho dá zapojiť šablonová dedičnosť. Pomocou toho by sa mali dať kvázi statické stránky s generickými prvkami.

**Comment by sstenchlak** [comment]
**Hlavní stránka:** Udělal bych nějakou generickou, klidně s mapkou, ale aby bylo poznat, že to není hlavní stránka Fyziklání. V dalších ročnících bychom ji pak mohli přepsat, pokud tam budeme mít třeba sponzory.

Je potřeba myslet na hlavní menu, které bychom mohli chtít v budoucnu pro nové archivní ročníky mít jiné.

Jinak s tím hlavním menu obecně, co tam mít obě menu? Teda to hlavní pro aktuální ročník a potom to pro archiv? Szmořejmě nějak to oddělit rozumně a viditelně, to by spíš byla otázka na grafika, nebo na vás, jestli vás něco nenapadne.
