### ISSUE TITLE
Stav soutěže

### ISSUE THREAD

**Issue by sstenchlak** [fykosak/web-fol#13]
Naimplementovat rozhraní, dle kterého je možné zjistit, v jakém stavu je soutěž. Bude se hodit i na FOF.

Uvažoval jsem, že bychom se mohli ptát, zda už proběhla nějaká událost

- soutěž začala existovat
- registrace otevřena
- herní den začal
- registrace uzavřena
- stream začal
- registrace uzavřena
- soutěž začala
- výsledkovky byly skryté
- soutěž skončila
- výsledkovky byly zobrazeny
- stream skončil
- herní den skončil
- herní víkend skončil
- soutěž skončila

To má výhodu například v období mezi koncem registrace a začátkem soutěže. Narážím na to, že alternativou by mohlo být zda nějaká událost právě probíhá (tedy `je soutěž`, `je otevřena registrace`, `je stream`) ale v obecném případě by se nám mohlo hodit vědět, zda už je po té akci, nebo ještě nebyla, kromě toho, zda vůbec probíhá, nebo ne.

Většina věcí by se pak odvíjela podle času, některé podle konfigurace (třeba ten stream) a některé by se mohly tahat z FKSDB.

Potom tu je ještě možnost se na to kompletně vykašlat a nemít obecné události, ale mít natvrdo funkce v kódu, které by mohly dávat i nějaké info navíc. Třeba zrovna u toho streamu bychom se pak nemuseli ptát na `isEventInProgress("STREAM")` ale mohli bychom mít rovnou `getStreamUrl(): string | null`.

@cevro

**Comment by cevro** [comment]
Obecne sa treba zamyslieť, čo na čom závisí, resp. odkiaľ sa to dá zistiť.

- soutěž začala existovat
  - toto znamená čo? vieme dátum? existuje event vo FKSDB (čo je IMO interná záležitosť)
- registrace otevřena
  - vieme dostať z FKSDB
- herní den začal
  - herný deň kde? tu v Indonézii? a keď hrajú cez polnoc, prip. iný deň (dáva to zmysel asi pri FOFe, a dá sa to vytiahnúť z FKSDB)
- registrace uzavřena
  - opäť sa dá vydolovať z FKSDB
- stream začal
  - viď dole
- soutěž začala
  - opať FKSDB
- výsledkovky byly skryté
  - teoreticky FKSDB (tab. game setup)
- soutěž skončila
  - opať FKSDB
- výsledkovky byly zobrazeny
  - opať FKSDB (tab. game setup)
- stream skončil
  - viď dole
- herní den skončil
  - to isté ako pri začiatku herného dňa
- herní víkend skončil
  - to isté ako pri začiatku herného dňa
- soutěž skončila
  - myslíš ako celý event pri FOFe
  
  
V hernom systéme FOLu sa používala taká magic, že sa veci vypĺňali v konfigu, teda ak existuje link na registráciu herný systém(starý web) sa tvári, že je registrácia spustená, teda plne stačí niekam do configu nahodiť nejaké parametre, ktoré sa nedajú inak zistiť, a podľa ich (ne)vyplnenia zisťovať stav.
```
getStreamUrl():?string{
    return $this->context->parameters['streamURL'];
}
```

**Comment by sstenchlak** [comment]
Ahoj, no point byl to mít nějak unifikované, teda nemít 10 různých tříd ze kterých si musíš tahat stav soutěže, ale mít jednu, která ví vše. Chtěl jsem to mít hlavně proto, aby to bylo jednoduché i pro řadové orgy, kdyby chtěl někdo něco upravit. Vím, že to moc nepomůže, ale přeci by se mohl někdo najít a určitě by mu to pomohlo.

```nette
{if $gameState->isAfter("registration_opened") && $gameState->isBefore("stream_started")}
PŘIHLAŠUJTE SE
{/if}
```

Ano, to že si to bude tahat z FKSDB a configů, tak jsem to myslel. Jen jsem uvažoval, že bychom to nějak sjednotili, aby v tom nebyl nepořádek.

Všechny stavy výše by znamenaly nějakou změnu UI. Pro upřesnění
- soutěž začala existovat znamená, že se tam zobrazí datum a nějaký text, že brzy bude spuštěná registrace. Před tím tam bude, že ještě datum nebyl rozhodnut
- herní den není myšlen explicitně den, ale období, kdy tam chceme už mít třeba odpočet a tlačítko s infem, jak se přihlásit, prostě info těsně před soutěží
- to samé s koncem dne a koncem víkendu
- soutěž skončila - třeba po měsíci, dáme pryč výsledkovky a stránka se přesune do archivu a bude to zase obyčejná generická stránka

Problém je, jak píšu, s těmi parametry. Že ty si vytáhneš z té hlavní třídy v jakém stavu je ta soutěž, ale stejně pak budeš muset sáhnout do příslušné jiné třídy, abys získal dodatečné info, jako třeba url streamu, čas do konce soutěže atd.

**Comment by cevro** [comment]
Nejaká implentácia:
https://github.com/fykosak/web-fol/blob/master/app/Models/GamePhaseCalculator.php

Ale asi by som to videl na viac rozmerov v ktorých by sa to malo pohybovať, pretože sa to odvíja od toho, že máme jasné poradie.

**Comment by sstenchlak** [comment]
Chceš to tedy zjednodušit tak, že máme jasné pořadí eventů, jo? Nemůže třeba nastat STREAM_BEGAN před REGISTRATION_ENDED ? Popřípadě chceme to povolit?

**Comment by cevro** [comment]
O tom hovorím, že tým, že z toho vytvoríš poradie môžeš určiť poradie, v podsatate na zavedenie znamienok `<` a `>` potrebuješ mat usporiadanie. 

Áno dá sa pýtať nastal event, ale napr. vieš iba, že stream je alebo nieje, nie to či skončil/nezačal. Môžeš povedať, že stream má stavy nezačal/beží/je záznam čo je detekovateľné, bez poradia. Alebo sa zmieriš s tým, že stream nezačne po konci eventu/resp. neskončí pred začiatok.
Teda sa dostávaš do podmienok, kde `hasStream &&  game.ended` a podobne kde opäť existuje nejaké usporiadanie množiny eventov.

Teda tu je shit kde by som IMO uvítal, viacrozmernosť, teda napr. má stream -> rob toto, a zároveň v inom rozmere rieši odpočet do/behom hry.

**Comment by sstenchlak** [comment]
Nechceme to nakonec udělat jednoduše tak, že ta třída bude mít spoustu metod jako `hasGameStarted` a `hasRegistrationClosed` a každá si nezávisle na ostatních zjistí, zda už ta událost proběhla? Teoreticky bychom tam pak mohli mít jiné typy metod, třeba `isStreamLive` u kterých by nedávalo smysl se ptát se, jestli ta akce proběhla, nebo proběhne, protože by mohla probáhat vícekrát opakovaně.

**Comment by sstenchlak** [comment]
Nějak už to implementováno je v `GamePhaseCalculator`u.
