### ISSUE TITLE
Komponenta o registraci

### ISSUE THREAD

**Issue by sstenchlak** [fykosak/web-fol#18]
Obdobně jako komponenta #16, uděláme komponentu, která bude zobrazovat čas do začátku registrace, nebo čas, kdy byla registrace spuštěna (bude se používat před otevřením registrace a krátce po ní). Pak bude nahrazena za #16, jakmile bude dost přihlášených týmů.

**Comment by katerinacharvatova** [comment]
časovač je hotový
