### ISSUE TITLE
Účastnícke preporty z akcie

### ISSUE THREAD

**Issue by cevro** [fykosak/web-fol#2]
Stránka ktorá zobrazí účastnícke reporty z danej akcie.  Vytvoriť DB štruktúru, použiť Fykosak\NetteORM. 

Pridávanie reportov zatiaľ neriešiť.

Inšpirovať sa https://github.com/fykosak/online-contest/blob/master/resources/db/schema-permanent.sql

**Comment by sstenchlak** [comment]
@vercah promiň, že jsem do toho zasáhl, chtěl jsem tam zkusit nahodit nový Tomášův design.

**Comment by sstenchlak** [comment]
Ok, tak Tomáš měl ještě nápad, že bychom vzali první fotku z reportu a dali ji float left nebo right (třeba zkusit, jak to bude vypadat), ať to není jen samý text.

**Comment by vercah** [comment]
Pokusila jsem se to přeskupit jako na obrázku s tím, že vedle textu vlevo je float container, ve kterém je box na velký obrázek a pod ním ty menší. Zatím se mi nepovedlo přijít na to, jak už při načtení stránky vyvolat tu funkci `gallery`, která by dala ten první obrázek velký (funguje mi jen onclick) a taky aby se u reportů, které nemají obrázky, nastavil ten celý container na `style.display = 'none'`.

**Comment by vercah** [comment]
Už to vypadá líp. Ještě by to chtělo asi vymyslet, jak to přeskupit u týmů, které mají jen fotky bez textu, protože to tam je takové prázdné; zatím mě nic hezkého nenapadá.

**Comment by sstenchlak** [comment]
Ahoj, ještě pozor na mobilní zařízení, ať i tam to vypadá pěkně :)
